FROM confluentinc/cp-kafka-connect:7.5.0

# Install MongoDB Kafka Connector if not already included
RUN confluent-hub install --no-prompt mongodb/kafka-connect-mongodb:1.11.0

# Make connectors available to the classpath
ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components"